apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-svc
spec:
  selector:
    app: {{ .Chart.Name }}
    component: frontend
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.service.frontend.targetPort }}
  type: {{ .Values.service.frontend.type }}