apiVersion: v1
data:
  tls.crt:***** # удалено в целях безопасности
  tls.key: **** # удалено в целях безопасности
kind: Secret
metadata:
  name: tls-secret
  namespace: default
type: kubernetes.io/tls